# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\supermarket4linux2.0\UI_File\userPayWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(578, 764)
        self.dialog = Dialog
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 20, 531, 381))
        self.groupBox_3.setObjectName("groupBox_3")
        self.itemInfoGroupbox1 = QtWidgets.QGroupBox(self.groupBox_3)
        self.itemInfoGroupbox1.setEnabled(True)
        self.itemInfoGroupbox1.setGeometry(QtCore.QRect(10, 20, 511, 51))
        self.itemInfoGroupbox1.setObjectName("itemInfoGroupbox1")
        self.layoutWidget = QtWidgets.QWidget(self.itemInfoGroupbox1)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 9, 491, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.item_name1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_name1.sizePolicy().hasHeightForWidth())
        self.item_name1.setSizePolicy(sizePolicy)
        self.item_name1.setObjectName("item_name1")
        self.horizontalLayout.addWidget(self.item_name1)
        self.item_weight1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_weight1.sizePolicy().hasHeightForWidth())
        self.item_weight1.setSizePolicy(sizePolicy)
        self.item_weight1.setObjectName("item_weight1")
        self.horizontalLayout.addWidget(self.item_weight1)
        self.item_simprice1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_simprice1.sizePolicy().hasHeightForWidth())
        self.item_simprice1.setSizePolicy(sizePolicy)
        self.item_simprice1.setObjectName("item_simprice1")
        self.horizontalLayout.addWidget(self.item_simprice1)
        self.item_toprice1 = QtWidgets.QLabel(self.layoutWidget)
        self.item_toprice1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_toprice1.sizePolicy().hasHeightForWidth())
        self.item_toprice1.setSizePolicy(sizePolicy)
        self.item_toprice1.setObjectName("item_toprice1")
        self.horizontalLayout.addWidget(self.item_toprice1)
        self.itemInfoGroupbox1_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.itemInfoGroupbox1_2.setEnabled(True)
        self.itemInfoGroupbox1_2.setGeometry(QtCore.QRect(10, 80, 511, 51))
        self.itemInfoGroupbox1_2.setObjectName("itemInfoGroupbox1_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.itemInfoGroupbox1_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 9, 491, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.item_name1_2 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_name1_2.sizePolicy().hasHeightForWidth())
        self.item_name1_2.setSizePolicy(sizePolicy)
        self.item_name1_2.setObjectName("item_name1_2")
        self.horizontalLayout_2.addWidget(self.item_name1_2)
        self.item_weight1_2 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_weight1_2.sizePolicy().hasHeightForWidth())
        self.item_weight1_2.setSizePolicy(sizePolicy)
        self.item_weight1_2.setObjectName("item_weight1_2")
        self.horizontalLayout_2.addWidget(self.item_weight1_2)
        self.item_simprice1_2 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_simprice1_2.sizePolicy().hasHeightForWidth())
        self.item_simprice1_2.setSizePolicy(sizePolicy)
        self.item_simprice1_2.setObjectName("item_simprice1_2")
        self.horizontalLayout_2.addWidget(self.item_simprice1_2)
        self.item_toprice1_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.item_toprice1_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_toprice1_2.sizePolicy().hasHeightForWidth())
        self.item_toprice1_2.setSizePolicy(sizePolicy)
        self.item_toprice1_2.setObjectName("item_toprice1_2")
        self.horizontalLayout_2.addWidget(self.item_toprice1_2)
        self.itemInfoGroupbox1_3 = QtWidgets.QGroupBox(self.groupBox_3)
        self.itemInfoGroupbox1_3.setEnabled(True)
        self.itemInfoGroupbox1_3.setGeometry(QtCore.QRect(10, 140, 511, 51))
        self.itemInfoGroupbox1_3.setObjectName("itemInfoGroupbox1_3")
        self.layoutWidget_3 = QtWidgets.QWidget(self.itemInfoGroupbox1_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 9, 491, 41))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.item_name1_3 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_name1_3.sizePolicy().hasHeightForWidth())
        self.item_name1_3.setSizePolicy(sizePolicy)
        self.item_name1_3.setObjectName("item_name1_3")
        self.horizontalLayout_3.addWidget(self.item_name1_3)
        self.item_weight1_3 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_weight1_3.sizePolicy().hasHeightForWidth())
        self.item_weight1_3.setSizePolicy(sizePolicy)
        self.item_weight1_3.setObjectName("item_weight1_3")
        self.horizontalLayout_3.addWidget(self.item_weight1_3)
        self.item_simprice1_3 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_simprice1_3.sizePolicy().hasHeightForWidth())
        self.item_simprice1_3.setSizePolicy(sizePolicy)
        self.item_simprice1_3.setObjectName("item_simprice1_3")
        self.horizontalLayout_3.addWidget(self.item_simprice1_3)
        self.item_toprice1_3 = QtWidgets.QLabel(self.layoutWidget_3)
        self.item_toprice1_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_toprice1_3.sizePolicy().hasHeightForWidth())
        self.item_toprice1_3.setSizePolicy(sizePolicy)
        self.item_toprice1_3.setObjectName("item_toprice1_3")
        self.horizontalLayout_3.addWidget(self.item_toprice1_3)
        self.itemInfoGroupbox1_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.itemInfoGroupbox1_4.setEnabled(True)
        self.itemInfoGroupbox1_4.setGeometry(QtCore.QRect(10, 200, 511, 51))
        self.itemInfoGroupbox1_4.setObjectName("itemInfoGroupbox1_4")
        self.layoutWidget_4 = QtWidgets.QWidget(self.itemInfoGroupbox1_4)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 9, 491, 41))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.item_name1_4 = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_name1_4.sizePolicy().hasHeightForWidth())
        self.item_name1_4.setSizePolicy(sizePolicy)
        self.item_name1_4.setObjectName("item_name1_4")
        self.horizontalLayout_4.addWidget(self.item_name1_4)
        self.item_weight1_4 = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_weight1_4.sizePolicy().hasHeightForWidth())
        self.item_weight1_4.setSizePolicy(sizePolicy)
        self.item_weight1_4.setObjectName("item_weight1_4")
        self.horizontalLayout_4.addWidget(self.item_weight1_4)
        self.item_simprice1_4 = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_simprice1_4.sizePolicy().hasHeightForWidth())
        self.item_simprice1_4.setSizePolicy(sizePolicy)
        self.item_simprice1_4.setObjectName("item_simprice1_4")
        self.horizontalLayout_4.addWidget(self.item_simprice1_4)
        self.item_toprice1_4 = QtWidgets.QLabel(self.layoutWidget_4)
        self.item_toprice1_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_toprice1_4.sizePolicy().hasHeightForWidth())
        self.item_toprice1_4.setSizePolicy(sizePolicy)
        self.item_toprice1_4.setObjectName("item_toprice1_4")
        self.horizontalLayout_4.addWidget(self.item_toprice1_4)
        self.itemInfoGroupbox1_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.itemInfoGroupbox1_5.setEnabled(True)
        self.itemInfoGroupbox1_5.setGeometry(QtCore.QRect(10, 260, 511, 51))
        self.itemInfoGroupbox1_5.setObjectName("itemInfoGroupbox1_5")
        self.layoutWidget_5 = QtWidgets.QWidget(self.itemInfoGroupbox1_5)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 9, 491, 41))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.item_name1_5 = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_name1_5.sizePolicy().hasHeightForWidth())
        self.item_name1_5.setSizePolicy(sizePolicy)
        self.item_name1_5.setObjectName("item_name1_5")
        self.horizontalLayout_5.addWidget(self.item_name1_5)
        self.item_weight1_5 = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_weight1_5.sizePolicy().hasHeightForWidth())
        self.item_weight1_5.setSizePolicy(sizePolicy)
        self.item_weight1_5.setObjectName("item_weight1_5")
        self.horizontalLayout_5.addWidget(self.item_weight1_5)
        self.item_simprice1_5 = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_simprice1_5.sizePolicy().hasHeightForWidth())
        self.item_simprice1_5.setSizePolicy(sizePolicy)
        self.item_simprice1_5.setObjectName("item_simprice1_5")
        self.horizontalLayout_5.addWidget(self.item_simprice1_5)
        self.item_toprice1_5 = QtWidgets.QLabel(self.layoutWidget_5)
        self.item_toprice1_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_toprice1_5.sizePolicy().hasHeightForWidth())
        self.item_toprice1_5.setSizePolicy(sizePolicy)
        self.item_toprice1_5.setObjectName("item_toprice1_5")
        self.horizontalLayout_5.addWidget(self.item_toprice1_5)
        self.itemInfoGroupbox1_6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.itemInfoGroupbox1_6.setEnabled(True)
        self.itemInfoGroupbox1_6.setGeometry(QtCore.QRect(10, 320, 511, 51))
        self.itemInfoGroupbox1_6.setObjectName("itemInfoGroupbox1_6")
        self.layoutWidget_6 = QtWidgets.QWidget(self.itemInfoGroupbox1_6)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 9, 491, 41))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.item_name1_6 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_name1_6.sizePolicy().hasHeightForWidth())
        self.item_name1_6.setSizePolicy(sizePolicy)
        self.item_name1_6.setObjectName("item_name1_6")
        self.horizontalLayout_6.addWidget(self.item_name1_6)
        self.item_weight1_6 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_weight1_6.sizePolicy().hasHeightForWidth())
        self.item_weight1_6.setSizePolicy(sizePolicy)
        self.item_weight1_6.setObjectName("item_weight1_6")
        self.horizontalLayout_6.addWidget(self.item_weight1_6)
        self.item_simprice1_6 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_simprice1_6.sizePolicy().hasHeightForWidth())
        self.item_simprice1_6.setSizePolicy(sizePolicy)
        self.item_simprice1_6.setObjectName("item_simprice1_6")
        self.horizontalLayout_6.addWidget(self.item_simprice1_6)
        self.item_toprice1_6 = QtWidgets.QLabel(self.layoutWidget_6)
        self.item_toprice1_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_toprice1_6.sizePolicy().hasHeightForWidth())
        self.item_toprice1_6.setSizePolicy(sizePolicy)
        self.item_toprice1_6.setObjectName("item_toprice1_6")
        self.horizontalLayout_6.addWidget(self.item_toprice1_6)
        self.ToPrice = QtWidgets.QLabel(Dialog)
        self.ToPrice.setGeometry(QtCore.QRect(320, 400, 231, 51))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(18)
        self.ToPrice.setFont(font)
        self.ToPrice.setObjectName("ToPrice")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 450, 531, 301))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 281, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.qrcode = QtWidgets.QLabel(self.groupBox_2)
        self.qrcode.setText("")
        self.qrcode.setObjectName("qrcode")
        self.horizontalLayout_7.addWidget(self.qrcode)
        self.cancelPaybtn = QtWidgets.QPushButton(self.groupBox)
        self.cancelPaybtn.setGeometry(QtCore.QRect(300, 180, 221, 61))
        self.cancelPaybtn.setObjectName("cancelPaybtn")
        self.helpInfo = QtWidgets.QLabel(self.groupBox)
        self.helpInfo.setGeometry(QtCore.QRect(300, 30, 221, 91))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(14)
        self.helpInfo.setFont(font)
        self.helpInfo.setObjectName("helpInfo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Pay Win"))
        self.groupBox_3.setTitle(_translate("Dialog", "购物清单"))
        self.itemInfoGroupbox1.setTitle(_translate("Dialog", "物品类别"))
        self.item_name1.setText(_translate("Dialog", "名称："))
        self.item_weight1.setText(_translate("Dialog", "重量："))
        self.item_simprice1.setText(_translate("Dialog", "单价："))
        self.item_toprice1.setText(_translate("Dialog", "总价："))
        self.itemInfoGroupbox1_2.setTitle(_translate("Dialog", "物品类别"))
        self.item_name1_2.setText(_translate("Dialog", "名称："))
        self.item_weight1_2.setText(_translate("Dialog", "重量："))
        self.item_simprice1_2.setText(_translate("Dialog", "单价："))
        self.item_toprice1_2.setText(_translate("Dialog", "总价："))
        self.itemInfoGroupbox1_3.setTitle(_translate("Dialog", "物品类别"))
        self.item_name1_3.setText(_translate("Dialog", "名称："))
        self.item_weight1_3.setText(_translate("Dialog", "重量："))
        self.item_simprice1_3.setText(_translate("Dialog", "单价："))
        self.item_toprice1_3.setText(_translate("Dialog", "总价："))
        self.itemInfoGroupbox1_4.setTitle(_translate("Dialog", "物品类别"))
        self.item_name1_4.setText(_translate("Dialog", "名称："))
        self.item_weight1_4.setText(_translate("Dialog", "重量："))
        self.item_simprice1_4.setText(_translate("Dialog", "单价："))
        self.item_toprice1_4.setText(_translate("Dialog", "总价："))
        self.itemInfoGroupbox1_5.setTitle(_translate("Dialog", "物品类别"))
        self.item_name1_5.setText(_translate("Dialog", "名称："))
        self.item_weight1_5.setText(_translate("Dialog", "重量："))
        self.item_simprice1_5.setText(_translate("Dialog", "单价："))
        self.item_toprice1_5.setText(_translate("Dialog", "总价："))
        self.itemInfoGroupbox1_6.setTitle(_translate("Dialog", "物品类别"))
        self.item_name1_6.setText(_translate("Dialog", "名称："))
        self.item_weight1_6.setText(_translate("Dialog", "重量："))
        self.item_simprice1_6.setText(_translate("Dialog", "单价："))
        self.item_toprice1_6.setText(_translate("Dialog", "总价："))
        self.ToPrice.setText(_translate("Dialog", "总价："))
        self.groupBox.setTitle(_translate("Dialog", "支付选项"))
        self.groupBox_2.setTitle(_translate("Dialog", "支付宝"))
        self.cancelPaybtn.setText(_translate("Dialog", "放弃支付"))
        self.helpInfo.setText(_translate("Dialog", "请在2分钟内完成支付！"))

        self.itemInfoGroupbox1.setHidden(True)
        self.itemInfoGroupbox1_2.setHidden(True)
        self.itemInfoGroupbox1_3.setHidden(True)
        self.itemInfoGroupbox1_4.setHidden(True)
        self.itemInfoGroupbox1_5.setHidden(True)
        self.itemInfoGroupbox1_6.setHidden(True)

        self.helpInfo.setWordWrap(True)


