# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\supermarket4linux2.0\UI_File\userInteractWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Choose WIN")
        Form.resize(1280, 800)
        self.form = Form
        self.cameraImg = QtWidgets.QLabel(Form)
        self.cameraImg.setEnabled(True)
        self.cameraImg.setGeometry(QtCore.QRect(30, 10, 621, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraImg.sizePolicy().hasHeightForWidth())
        self.cameraImg.setSizePolicy(sizePolicy)
        self.cameraImg.setText("")
        self.cameraImg.setObjectName("cameraImg")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(690, 10, 551, 371))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 491, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.objName = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(26)
        self.objName.setFont(font)
        self.objName.setText("")
        self.objName.setObjectName("objName")
        self.gridLayout.addWidget(self.objName, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(26)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.objWeight = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(26)
        self.objWeight.setFont(font)
        self.objWeight.setText("")
        self.objWeight.setObjectName("objWeight")
        self.gridLayout.addWidget(self.objWeight, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(26)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.simPrice = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(26)
        self.simPrice.setFont(font)
        self.simPrice.setText("")
        self.simPrice.setObjectName("simPrice")
        self.gridLayout.addWidget(self.simPrice, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(26)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.totalPrice = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(26)
        self.totalPrice.setFont(font)
        self.totalPrice.setText("")
        self.totalPrice.setObjectName("totalPrice")
        self.gridLayout.addWidget(self.totalPrice, 3, 1, 1, 1)
        self.itemSelectbtn = QtWidgets.QPushButton(self.groupBox)
        self.itemSelectbtn.setGeometry(QtCore.QRect(50, 300, 451, 61))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(24)
        self.itemSelectbtn.setFont(font)
        self.itemSelectbtn.setIconSize(QtCore.QSize(100, 100))
        self.itemSelectbtn.setObjectName("itemSelectbtn")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 390, 621, 381))
        self.groupBox_3.setObjectName("groupBox_3")
        self.itemInfoGroupbox1 = QtWidgets.QGroupBox(self.groupBox_3)
        self.itemInfoGroupbox1.setEnabled(True)
        self.itemInfoGroupbox1.setGeometry(QtCore.QRect(20, 20, 561, 51))
        self.itemInfoGroupbox1.setObjectName("itemInfoGroupbox1")
        self.layoutWidget1 = QtWidgets.QWidget(self.itemInfoGroupbox1)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 541, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.item_name1 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_name1.sizePolicy().hasHeightForWidth())
        self.item_name1.setSizePolicy(sizePolicy)
        self.item_name1.setObjectName("item_name1")
        self.horizontalLayout.addWidget(self.item_name1)
        self.item_weight1 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_weight1.sizePolicy().hasHeightForWidth())
        self.item_weight1.setSizePolicy(sizePolicy)
        self.item_weight1.setObjectName("item_weight1")
        self.horizontalLayout.addWidget(self.item_weight1)
        self.item_simprice1 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_simprice1.sizePolicy().hasHeightForWidth())
        self.item_simprice1.setSizePolicy(sizePolicy)
        self.item_simprice1.setObjectName("item_simprice1")
        self.horizontalLayout.addWidget(self.item_simprice1)
        self.item_toprice1 = QtWidgets.QLabel(self.layoutWidget1)
        self.item_toprice1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_toprice1.sizePolicy().hasHeightForWidth())
        self.item_toprice1.setSizePolicy(sizePolicy)
        self.item_toprice1.setObjectName("item_toprice1")
        self.horizontalLayout.addWidget(self.item_toprice1)
        self.cancelbtn1 = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelbtn1.sizePolicy().hasHeightForWidth())
        self.cancelbtn1.setSizePolicy(sizePolicy)
        self.cancelbtn1.setObjectName("cancelbtn1")
        self.horizontalLayout.addWidget(self.cancelbtn1)
        self.itemInfoGroupbox2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.itemInfoGroupbox2.setGeometry(QtCore.QRect(20, 80, 561, 51))
        self.itemInfoGroupbox2.setObjectName("itemInfoGroupbox2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.itemInfoGroupbox2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 9, 541, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.item_name2 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_name2.sizePolicy().hasHeightForWidth())
        self.item_name2.setSizePolicy(sizePolicy)
        self.item_name2.setObjectName("item_name2")
        self.horizontalLayout_2.addWidget(self.item_name2)
        self.item_weight2 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_weight2.sizePolicy().hasHeightForWidth())
        self.item_weight2.setSizePolicy(sizePolicy)
        self.item_weight2.setObjectName("item_weight2")
        self.horizontalLayout_2.addWidget(self.item_weight2)
        self.item_simprice2 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_simprice2.sizePolicy().hasHeightForWidth())
        self.item_simprice2.setSizePolicy(sizePolicy)
        self.item_simprice2.setObjectName("item_simprice2")
        self.horizontalLayout_2.addWidget(self.item_simprice2)
        self.item_toprice2 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_toprice2.sizePolicy().hasHeightForWidth())
        self.item_toprice2.setSizePolicy(sizePolicy)
        self.item_toprice2.setObjectName("item_toprice2")
        self.horizontalLayout_2.addWidget(self.item_toprice2)
        self.cancelbtn2 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelbtn2.sizePolicy().hasHeightForWidth())
        self.cancelbtn2.setSizePolicy(sizePolicy)
        self.cancelbtn2.setObjectName("cancelbtn2")
        self.horizontalLayout_2.addWidget(self.cancelbtn2)
        self.itemInfoGroupbox3 = QtWidgets.QGroupBox(self.groupBox_3)
        self.itemInfoGroupbox3.setGeometry(QtCore.QRect(20, 140, 561, 51))
        self.itemInfoGroupbox3.setObjectName("itemInfoGroupbox3")
        self.layoutWidget_3 = QtWidgets.QWidget(self.itemInfoGroupbox3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 9, 541, 41))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.item_name3 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_name3.sizePolicy().hasHeightForWidth())
        self.item_name3.setSizePolicy(sizePolicy)
        self.item_name3.setObjectName("item_name3")
        self.horizontalLayout_3.addWidget(self.item_name3)
        self.item_weight3 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_weight3.sizePolicy().hasHeightForWidth())
        self.item_weight3.setSizePolicy(sizePolicy)
        self.item_weight3.setObjectName("item_weight3")
        self.horizontalLayout_3.addWidget(self.item_weight3)
        self.item_simprice3 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_simprice3.sizePolicy().hasHeightForWidth())
        self.item_simprice3.setSizePolicy(sizePolicy)
        self.item_simprice3.setObjectName("item_simprice3")
        self.horizontalLayout_3.addWidget(self.item_simprice3)
        self.item_toprice3 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_toprice3.sizePolicy().hasHeightForWidth())
        self.item_toprice3.setSizePolicy(sizePolicy)
        self.item_toprice3.setObjectName("item_toprice3")
        self.horizontalLayout_3.addWidget(self.item_toprice3)
        self.cancelbtn3 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelbtn3.sizePolicy().hasHeightForWidth())
        self.cancelbtn3.setSizePolicy(sizePolicy)
        self.cancelbtn3.setObjectName("cancelbtn3")
        self.horizontalLayout_3.addWidget(self.cancelbtn3)
        self.itemInfoGroupbox4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.itemInfoGroupbox4.setGeometry(QtCore.QRect(20, 200, 561, 51))
        self.itemInfoGroupbox4.setObjectName("itemInfoGroupbox4")
        self.layoutWidget_4 = QtWidgets.QWidget(self.itemInfoGroupbox4)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 9, 541, 41))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.item_name4 = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_name4.sizePolicy().hasHeightForWidth())
        self.item_name4.setSizePolicy(sizePolicy)
        self.item_name4.setObjectName("item_name4")
        self.horizontalLayout_4.addWidget(self.item_name4)
        self.item_weight4 = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_weight4.sizePolicy().hasHeightForWidth())
        self.item_weight4.setSizePolicy(sizePolicy)
        self.item_weight4.setObjectName("item_weight4")
        self.horizontalLayout_4.addWidget(self.item_weight4)
        self.item_simprice4 = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_simprice4.sizePolicy().hasHeightForWidth())
        self.item_simprice4.setSizePolicy(sizePolicy)
        self.item_simprice4.setObjectName("item_simprice4")
        self.horizontalLayout_4.addWidget(self.item_simprice4)
        self.item_toprice4 = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_toprice4.sizePolicy().hasHeightForWidth())
        self.item_toprice4.setSizePolicy(sizePolicy)
        self.item_toprice4.setObjectName("item_toprice4")
        self.horizontalLayout_4.addWidget(self.item_toprice4)
        self.cancelbtn4 = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelbtn4.sizePolicy().hasHeightForWidth())
        self.cancelbtn4.setSizePolicy(sizePolicy)
        self.cancelbtn4.setObjectName("cancelbtn4")
        self.horizontalLayout_4.addWidget(self.cancelbtn4)
        self.itemInfoGroupbox5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.itemInfoGroupbox5.setGeometry(QtCore.QRect(20, 260, 561, 51))
        self.itemInfoGroupbox5.setObjectName("itemInfoGroupbox5")
        self.layoutWidget_5 = QtWidgets.QWidget(self.itemInfoGroupbox5)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 9, 541, 41))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.item_name5 = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_name5.sizePolicy().hasHeightForWidth())
        self.item_name5.setSizePolicy(sizePolicy)
        self.item_name5.setObjectName("item_name5")
        self.horizontalLayout_5.addWidget(self.item_name5)
        self.item_weight5 = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_weight5.sizePolicy().hasHeightForWidth())
        self.item_weight5.setSizePolicy(sizePolicy)
        self.item_weight5.setObjectName("item_weight5")
        self.horizontalLayout_5.addWidget(self.item_weight5)
        self.item_simprice5 = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_simprice5.sizePolicy().hasHeightForWidth())
        self.item_simprice5.setSizePolicy(sizePolicy)
        self.item_simprice5.setObjectName("item_simprice5")
        self.horizontalLayout_5.addWidget(self.item_simprice5)
        self.item_toprice5 = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_toprice5.sizePolicy().hasHeightForWidth())
        self.item_toprice5.setSizePolicy(sizePolicy)
        self.item_toprice5.setObjectName("item_toprice5")
        self.horizontalLayout_5.addWidget(self.item_toprice5)
        self.cancelbtn5 = QtWidgets.QPushButton(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelbtn5.sizePolicy().hasHeightForWidth())
        self.cancelbtn5.setSizePolicy(sizePolicy)
        self.cancelbtn5.setObjectName("cancelbtn5")
        self.horizontalLayout_5.addWidget(self.cancelbtn5)
        self.itemInfoGroupbox6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.itemInfoGroupbox6.setGeometry(QtCore.QRect(20, 320, 561, 51))
        self.itemInfoGroupbox6.setObjectName("itemInfoGroupbox6")
        self.layoutWidget_6 = QtWidgets.QWidget(self.itemInfoGroupbox6)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 9, 541, 41))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.item_name6 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_name6.sizePolicy().hasHeightForWidth())
        self.item_name6.setSizePolicy(sizePolicy)
        self.item_name6.setObjectName("item_name6")
        self.horizontalLayout_6.addWidget(self.item_name6)
        self.item_weight6 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_weight6.sizePolicy().hasHeightForWidth())
        self.item_weight6.setSizePolicy(sizePolicy)
        self.item_weight6.setObjectName("item_weight6")
        self.horizontalLayout_6.addWidget(self.item_weight6)
        self.item_simprice6 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_simprice6.sizePolicy().hasHeightForWidth())
        self.item_simprice6.setSizePolicy(sizePolicy)
        self.item_simprice6.setObjectName("item_simprice6")
        self.horizontalLayout_6.addWidget(self.item_simprice6)
        self.item_toprice6 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_toprice6.sizePolicy().hasHeightForWidth())
        self.item_toprice6.setSizePolicy(sizePolicy)
        self.item_toprice6.setObjectName("item_toprice6")
        self.horizontalLayout_6.addWidget(self.item_toprice6)
        self.cancelbtn6 = QtWidgets.QPushButton(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelbtn6.sizePolicy().hasHeightForWidth())
        self.cancelbtn6.setSizePolicy(sizePolicy)
        self.cancelbtn6.setObjectName("cancelbtn6")
        self.horizontalLayout_6.addWidget(self.cancelbtn6)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(690, 390, 551, 161))
        self.groupBox_4.setObjectName("groupBox_4")
        self.guideInfoLabel = QtWidgets.QLabel(self.groupBox_4)
        self.guideInfoLabel.setGeometry(QtCore.QRect(20, 30, 531, 111))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(14)
        self.guideInfoLabel.setFont(font)
        self.guideInfoLabel.setText("")
        self.guideInfoLabel.setObjectName("guideInfoLabel")
        self.confirmedPaybtn = QtWidgets.QPushButton(Form)
        self.confirmedPaybtn.setGeometry(QtCore.QRect(690, 560, 351, 161))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(24)
        self.confirmedPaybtn.setFont(font)
        self.confirmedPaybtn.setIconSize(QtCore.QSize(100, 100))
        self.confirmedPaybtn.setObjectName("confirmedPaybtn")
        self.exit2initial = QtWidgets.QPushButton(Form)
        self.exit2initial.setGeometry(QtCore.QRect(1060, 560, 181, 161))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(24)
        self.exit2initial.setFont(font)
        self.exit2initial.setIconSize(QtCore.QSize(100, 100))
        self.exit2initial.setObjectName("exit2initial")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Choose Win"))
        self.groupBox.setTitle(_translate("Form", "物品信息"))
        self.label.setText(_translate("Form", "名称："))
        self.label_3.setText(_translate("Form", "重量："))
        self.label_5.setText(_translate("Form", "单价："))
        self.label_7.setText(_translate("Form", "总价："))
        self.itemSelectbtn.setText(_translate("Form", "确认选择"))
        self.groupBox_3.setTitle(_translate("Form", "预购清单"))
        self.itemInfoGroupbox1.setTitle(_translate("Form", "物品类别"))
        self.item_name1.setText(_translate("Form", "名称:"))
        self.item_weight1.setText(_translate("Form", "重量:"))
        self.item_simprice1.setText(_translate("Form", "单价:"))
        self.item_toprice1.setText(_translate("Form", "总价:"))
        self.cancelbtn1.setText(_translate("Form", "取消选择"))
        self.itemInfoGroupbox2.setTitle(_translate("Form", "物品类别"))
        self.item_name2.setText(_translate("Form", "名称:"))
        self.item_weight2.setText(_translate("Form", "重量:"))
        self.item_simprice2.setText(_translate("Form", "单价:"))
        self.item_toprice2.setText(_translate("Form", "总价:"))
        self.cancelbtn2.setText(_translate("Form", "取消选择"))
        self.itemInfoGroupbox3.setTitle(_translate("Form", "物品类别"))
        self.item_name3.setText(_translate("Form", "名称:"))
        self.item_weight3.setText(_translate("Form", "重量:"))
        self.item_simprice3.setText(_translate("Form", "单价:"))
        self.item_toprice3.setText(_translate("Form", "总价:"))
        self.cancelbtn3.setText(_translate("Form", "取消选择"))
        self.itemInfoGroupbox4.setTitle(_translate("Form", "物品类别"))
        self.item_name4.setText(_translate("Form", "名称:"))
        self.item_weight4.setText(_translate("Form", "重量:"))
        self.item_simprice4.setText(_translate("Form", "单价:"))
        self.item_toprice4.setText(_translate("Form", "总价:"))
        self.cancelbtn4.setText(_translate("Form", "取消选择"))
        self.itemInfoGroupbox5.setTitle(_translate("Form", "物品类别"))
        self.item_name5.setText(_translate("Form", "名称:"))
        self.item_weight5.setText(_translate("Form", "重量:"))
        self.item_simprice5.setText(_translate("Form", "单价:"))
        self.item_toprice5.setText(_translate("Form", "总价:"))
        self.cancelbtn5.setText(_translate("Form", "取消选择"))
        self.itemInfoGroupbox6.setTitle(_translate("Form", "物品类别"))
        self.item_name6.setText(_translate("Form", "名称:"))
        self.item_weight6.setText(_translate("Form", "重量:"))
        self.item_simprice6.setText(_translate("Form", "单价:"))
        self.item_toprice6.setText(_translate("Form", "总价:"))
        self.cancelbtn6.setText(_translate("Form", "取消选择"))
        self.groupBox_4.setTitle(_translate("Form", "操作提示"))
        self.confirmedPaybtn.setText(_translate("Form", "确认支付"))
        self.exit2initial.setText(_translate("Form", "退出"))

        self.itemInfoGroupbox1.setVisible(False)
        self.itemInfoGroupbox2.setVisible(False)
        self.itemInfoGroupbox3.setVisible(False)
        self.itemInfoGroupbox4.setVisible(False)
        self.itemInfoGroupbox5.setVisible(False)
        self.itemInfoGroupbox6.setVisible(False)

        self.guideInfoLabel.setWordWrap(True)

